name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
