name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}
    - name: Create and activate venv
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies in venv
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install scipy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
